#!/usr/bin/env python
"""
Step 2 of 2. Draw every figure in the paper.

This script reads ONLY the outputs of step 1 (results.json and
events_derived.csv). It never re-opens the raw data and never recomputes a
statistic. That is deliberate: it makes it impossible for a figure to disagree
with the text, and it means the figures can be regenerated by a reader who has
results.json but not the ISC exports.

Usage
-----
    python scripts/02_make_figures.py --results OUT_DIR --output FIG_DIR
"""

import argparse
import json
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(sys.argv[0])), ".."))

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from matplotlib.ticker import MultipleLocator


def style(cfg):
    f = cfg["figures"]

    plt.rcParams.update({
        "font.family": "DejaVu Sans",
        "font.size": f["font_size_pt"],
        "axes.linewidth": 0.7,
        "axes.edgecolor": f["colour_ink_soft"],
        "xtick.color": f["colour_ink_soft"],
        "ytick.color": f["colour_ink_soft"],
        "text.color": f["colour_ink"],
        "axes.labelcolor": f["colour_ink"],
        "xtick.major.width": 0.7,
        "ytick.major.width": 0.7,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "figure.dpi": 150,
        "savefig.dpi": f["dpi"],
        "pdf.fonttype": 42, "ps.fonttype": 42,
    })
    return f


def save(fig, out_dir, name):
    """
    Write each figure in four formats from a single figure object, so that the
    versions cannot disagree.

    EPS and TIFF meet the SSA production requirements for vector line art and
    for combination art at the configured resolution. PDF keeps the text
    editable and PNG is for quick viewing.
    """
    written = []
    for ext in ("pdf", "png", "eps", "tif"):
        try:
            fig.savefig(os.path.join(out_dir, "%s.%s" % (name, ext)),
                        bbox_inches="tight")
            written.append(ext)
        except Exception as exc:                       # e.g. no TIFF support
            print("    (skipped %s: %s)" % (ext, exc))
    plt.close(fig)
    print("  %s -> %s" % (name, ", ".join(written)))


def figure_station_event_map(res, ev, sta, C, out_dir):
    """
    Location map: the epicenters analyzed and the stations that recorded them.

    The whole argument of the paper is geometric, so the reader needs to see
    where the events are and where the recording stations are not. Panel (a)
    is the study rectangle; panel (b) widens to the stations that contribute
    arrivals from outside it, which is why the Bulletin's reported gap is a
    global quantity.
    """
    box = res["configuration"]["study_area"]
    prim = ev[ev["period"] == "primary"]

    fig, axes = plt.subplots(1, 2, figsize=(7.2, 3.6))
    fig.subplots_adjust(wspace=0.32)

    ax = axes[0]
    ax.scatter(prim["lon"], prim["lat"], s=3, c=C["colour_series_1"],
               alpha=0.30, linewidths=0, label="Epicenters (n=%d)" % len(prim),
               rasterized=True)
    inside = sta[(sta["lat"].between(box["lat_min"], box["lat_max"])) &
                 (sta["lon"].between(box["lon_min"], box["lon_max"]))]
    ax.scatter(inside["lon"], inside["lat"], s=26,
               marker="^", facecolor=C["colour_series_2"],
               edgecolor="white", linewidths=0.5, zorder=5,
               label="Stations in box (n=%d)" % len(inside))
    tb = res["configuration"]["study_area"]["target"]
    ax.add_patch(plt.Rectangle((tb["lon_min"], tb["lat_min"]),
                               tb["lon_max"] - tb["lon_min"],
                               tb["lat_max"] - tb["lat_min"],
                               fill=False, ec=C["colour_ink_soft"],
                               lw=0.9, ls="--", zorder=6))
    ax.set_xlim(box["lon_min"], box["lon_max"])
    ax.set_ylim(box["lat_min"], box["lat_max"])
    ax.set_aspect(1.0 / np.cos(np.deg2rad(0.5 * (box["lat_min"] + box["lat_max"]))))
    ax.set_xlabel("Longitude (deg E)")
    ax.set_ylabel("Latitude (deg N)")
    ax.legend(loc="lower left", fontsize=6.5, frameon=False, handletextpad=0.4)
    ax.set_title("a   Epicenters and stations inside the study area",
                 loc="left", fontsize=8.0, pad=6)

    ax = axes[1]
    near = sta[(sta["lat"].between(box["lat_min"] - 8, box["lat_max"] + 8)) &
               (sta["lon"].between(box["lon_min"] - 8, box["lon_max"] + 8))]
    ax.scatter(near["lon"], near["lat"], s=9, marker="^",
               facecolor=C["colour_series_2"], edgecolor="none",
               alpha=0.75, label="Stations (n=%d)" % len(near))
    ax.scatter(prim["lon"], prim["lat"], s=2, c=C["colour_series_1"],
               alpha=0.25, linewidths=0, rasterized=True, label="Epicenters")
    ax.add_patch(plt.Rectangle((box["lon_min"], box["lat_min"]),
                               box["lon_max"] - box["lon_min"],
                               box["lat_max"] - box["lat_min"],
                               fill=False, ec=C["colour_ink"], lw=1.1, zorder=6))
    ax.set_xlim(box["lon_min"] - 8, box["lon_max"] + 8)
    ax.set_ylim(box["lat_min"] - 8, box["lat_max"] + 8)
    ax.set_aspect(1.0 / np.cos(np.deg2rad(0.5 * (box["lat_min"] + box["lat_max"]))))
    ax.set_xlabel("Longitude (deg E)")
    ax.set_ylabel("Latitude (deg N)")
    ax.legend(loc="upper left", fontsize=6.5, frameon=False, handletextpad=0.4)
    ax.set_title("b   The recording network at regional scale",
                 loc="left", fontsize=8.0, pad=6)

    save(fig, out_dir, "fig02_station_event_map")


def figure_depth_quantization(res, ev, C, out_dir):
    q = res["depth_quantization"]
    # Plot only the reviewed primary period, so that the histogram is drawn from
    # the same events as every number reported in results.json and in the text.
    if "period" in ev.columns:
        ev = ev[ev["period"] == "primary"]
    fig, axes = plt.subplots(1, 2, figsize=(7.2, 2.7),
                             gridspec_kw={"width_ratios": [2.1, 1]})

    ax = axes[0]
    depth = ev["depth_km"].dropna()
    hist, edges = np.histogram(depth, bins=np.arange(0, 61, 1))
    ax.bar(edges[:-1], hist, width=0.85, color=C["colour_neutral"], linewidth=0)

    marked = [(10.0, q["operational_values"]["10.0"]["percent"]),
              (24.0, q["operational_values"]["24.0"]["percent"])]
    for value, pct in marked:
        idx = int(value)
        ax.bar([value], [hist[idx]], width=0.85,
               color=C["colour_series_2"], linewidth=0)
        ax.annotate("%.1f km\n%.1f%% of all events" % (value, pct),
                    xy=(value, hist[idx]), xytext=(value + 3.5, hist[idx] * 0.94),
                    fontsize=7.5, ha="left", va="top", color=C["colour_ink"],
                    arrowprops=dict(arrowstyle="-", lw=0.6,
                                    color=C["colour_ink_soft"]))
    ax.set_xlabel("Catalog focal depth (km)")
    ax.set_ylabel("Number of events")
    ax.set_xlim(0, 60)
    ax.xaxis.set_major_locator(MultipleLocator(10))
    ax.set_title("a   Reported depths, %d–%d (n = %d)"
                 % (res["dataset"]["first_year"], res["dataset"]["last_year"],
                    q["n_events_with_depth"]),
                 loc="left", fontsize=8.5, pad=6)

    ax = axes[1]
    pct_int = q["percent_integer_valued"]
    ax.barh([1, 0], [pct_int, 100.0 - pct_int],
            color=[C["colour_series_2"], C["colour_neutral"]],
            height=0.5, linewidth=0)
    for y, v, label in [(1, pct_int, "integer-valued"),
                        (0, 100.0 - pct_int, "non-integer")]:
        ax.text(v + 2.0, y, "%s\n%.1f%%" % (label, v), va="center",
                fontsize=7.5, color=C["colour_ink"])
    ax.set_xlim(0, 100)
    ax.set_yticks([])
    ax.set_xlabel("Percentage of events")
    ax.set_title("b   Depth quantization", loc="left", fontsize=8.5, pad=6)
    save(fig, out_dir, "fig03_depth_quantization")


def figure_agency_confounding(res, ev, C, out_dir):
    a = res["agency_confounding"]
    rows = pd.DataFrame(a["per_year"])
    agencies = a["agencies_reported_individually"]
    lead = max(agencies, key=lambda g: a["per_agency"][g]["n"])
    other = [g for g in agencies if g != lead]

    fig, axes = plt.subplots(2, 1, figsize=(5.6, 4.5), sharex=True,
                             gridspec_kw={"height_ratios": [1, 1.5],
                                          "hspace": 0.16})
    ax = axes[0]
    ax.bar(rows["year"], rows["share_%s_percent" % lead],
           color=C["colour_series_3"], width=0.65, linewidth=0)
    ax.set_ylabel("%s share of prime\nhypocenters (%%)" % lead)
    ax.set_ylim(0, 100)
    ax.set_title("a   The mix of reporting agencies changes through time",
                 loc="left", fontsize=8.5, pad=6)

    ax = axes[1]
    evp = ev[ev["period"] == "primary"] if "period" in ev.columns else ev
    pooled_yearly = (evp.assign(year=evp["date"].str[:4].astype(int))
                        .dropna(subset=["depth_km"])
                        .groupby("year")["depth_km"].median())
    ax.plot(pooled_yearly.index, pooled_yearly.values, "-o",
            color=C["colour_ink"], lw=2, ms=3.5, mec="white", mew=0.7, zorder=5,
            label="Pooled catalog, yearly median")
    palette = [C["colour_series_1"], C["colour_series_2"]]
    markers = ["o", "s"]
    for i, agency in enumerate([g for g in agencies if g in (lead,) or g in other][:2]):
        ax.plot(rows["year"], rows["median_%s_km" % agency], "-",
                marker=markers[i % 2], color=palette[i % 2], lw=2, ms=4.5,
                mec="white", mew=0.8, label="%s solutions only" % agency)
    ax.set_ylabel("Median focal depth (km)")
    ax.set_xlabel("Year")
    ax.legend(frameon=False, fontsize=7.5, loc="lower left")
    ax.set_ylim(4, 27)
    ax.text(rows["year"].min() + 0.1, 22.6,
            "pooled median falls from %.0f to %.0f km, while the\nagency "
            "medians show no downward trend"
            % (pooled_yearly.values[0], pooled_yearly.values[-1]),
            fontsize=7, ha="left", va="bottom", color=C["colour_ink"])
    ax.set_title("b   The pooled trend follows the agency mix",
                 loc="left", fontsize=8.5, pad=6)
    save(fig, out_dir, "fig04_agency_confounding")


def figure_gap_versus_cutoff(res, ev, C, out_dir):
    rows = pd.DataFrame(res["gap_versus_distance_cutoff"]["rows"])
    labels = ["all" if pd.isna(c) or c is None else "%g" % c
              for c in rows["cutoff_km"]]
    x = np.arange(len(rows))

    fig, ax = plt.subplots(figsize=(5.6, 3.1))
    ax.fill_between(x, rows["p25_gap_deg"], rows["p75_gap_deg"],
                    color=C["colour_series_1"], alpha=0.16, linewidth=0)
    ax.plot(x, rows["median_gap_deg"], "-o", color=C["colour_series_1"],
            lw=2, ms=5, mec="white", mew=0.9)
    ax.axhline(res["configuration"]["thresholds"]["max_gap_deg"],
               color=C["colour_series_2"], lw=1.2, ls=(0, (4, 2)))
    ax.text(0.12, res["configuration"]["thresholds"]["max_gap_deg"] + 7,
            "%d°: depth poorly constrained above this line"
            % res["configuration"]["thresholds"]["max_gap_deg"],
            fontsize=7, color=C["colour_series_2"])

    for i, (dx, dy, ha) in zip([2, 4, len(rows) - 1],
                               [(0.18, -32, "left"), (0.18, 14, "left"),
                                (-0.18, 14, "right")]):
        ax.annotate("%.0f°" % rows["median_gap_deg"].iloc[i],
                    xy=(x[i], rows["median_gap_deg"].iloc[i]),
                    xytext=(x[i] + dx, rows["median_gap_deg"].iloc[i] + dy),
                    fontsize=8, ha=ha, color=C["colour_ink"])

    ax.set_xticks(x)
    ax.set_xticklabels(labels)
    ax.set_xlim(-0.5, len(rows) - 0.3)
    ax.set_ylim(0, 392)
    ax.yaxis.set_major_locator(MultipleLocator(90))
    ax.set_xlabel("Stations retained within this epicentral distance (km)")
    ax.set_ylabel("Azimuthal gap (°)")
    ax.set_title("Azimuthal gap recomputed at a series of distance cut-offs\n"
                 "(line = median, shading = interquartile range, n = %d events)"
                 % res["dataset"]["n_events"],
                 loc="left", fontsize=8.5, pad=6)
    save(fig, out_dir, "fig05_gap_versus_cutoff")


def figure_network_capability(res, ev, C, out_dir):
    n = res["network_capability"]
    # Plot only the reviewed primary period, so that the histogram is drawn from
    # the same events as every number reported in results.json and in the text.
    if "period" in ev.columns:
        ev = ev[ev["period"] == "primary"]
    detach = res["configuration"]["physics"]["detachment_depth_km"]
    max_gap = res["configuration"]["thresholds"]["max_gap_deg"]
    min_sta = res["configuration"]["thresholds"]["min_stations"]
    local_km = res["configuration"]["thresholds"]["local_network_km"]

    fig, axes = plt.subplots(1, 2, figsize=(7.2, 2.9))

    ax = axes[0]
    nearest = ev["nearest_station_km"].dropna()
    ax.hist(nearest, bins=np.logspace(0, 3, 40),
            color=C["colour_neutral"], linewidth=0)
    ax.axvline(detach, color=C["colour_series_2"], lw=1.2, ls=(0, (4, 2)))
    ax.set_xscale("log")
    ax.set_xlabel("Distance to the nearest recording station (km)")
    ax.set_ylabel("Number of events")
    ax.text(detach * 1.15, ax.get_ylim()[1] * 0.93,
            "%.0f km:\nreference depth" % detach,
            fontsize=7, color=C["colour_series_2"], va="top")
    ax.text(0.97, 0.52,
            "%.1f%% of events have a station\ncloser than that depth"
            % n["percent_with_station_closer_than_detachment"],
            transform=ax.transAxes, ha="right", fontsize=7,
            color=C["colour_ink"])
    ax.set_title("a   Distance to the nearest station",
                 loc="left", fontsize=8.5, pad=6)

    ax = axes[1]
    ax.scatter(ev["n_stations_local"], ev["gap_local_deg"], s=5,
               color=C["colour_series_1"], alpha=0.25, linewidths=0)
    ax.axhline(max_gap, color=C["colour_series_2"], lw=1.2, ls=(0, (4, 2)))
    ax.axvline(min_sta - 0.5, color=C["colour_series_2"], lw=1.2, ls=(0, (4, 2)))
    ax.set_xlabel("Stations within %d km" % local_km)
    ax.set_ylabel("Azimuthal gap of those stations (°)")
    ax.set_xlim(0.3, max(9.2, ev["n_stations_local"].max() + 1))
    ax.set_ylim(0, 375)
    ax.yaxis.set_major_locator(MultipleLocator(90))
    ax.text(0.97, 0.06,
            "%d of %d events reach\n≥%d stations and gap < %d°"
            % (n["n_well_constrained"], n["n_events"], min_sta, max_gap),
            transform=ax.transAxes, ha="right", fontsize=7,
            color=C["colour_ink"])
    ax.set_title("b   Station count against azimuthal gap",
                 loc="left", fontsize=8.5, pad=6)
    save(fig, out_dir, "fig06_network_capability")


def figure_recent_era(res, ev, C, out_dir):
    """
    The recent, unreviewed years: the agency mix turns over again, and two of
    the newcomers report a depth column that never varies.

    Panel (b) plots the depth values themselves rather than a summary, because
    the point is the absence of spread. Vertical positions within each row are
    a deterministic fan (index-based, not random), so the figure is identical
    on every run.
    """
    r = res["recent_era"]
    comp = pd.DataFrame(r["composition_by_year"])
    agencies = r["agencies_reported"]

    # Order agencies by how many events they contributed, largest first.
    order = sorted(agencies, key=lambda a: -r["by_agency"][a]["n"])
    invariant = set(r["agencies_with_invariant_depth"])

    fig, axes = plt.subplots(1, 2, figsize=(7.2, 3.5),
                             gridspec_kw={"width_ratios": [1, 1.35],
                                          "wspace": 0.32})

    ax = axes[0]
    palette = [C["colour_series_1"], C["colour_series_2"], C["colour_series_3"],
               C["colour_neutral"]]
    bottom = np.zeros(len(comp))
    top_three = order[:3]
    for i, agency in enumerate(top_three):
        vals = np.array([row.get(agency, 0.0) for row in comp["shares_percent"]])
        ax.bar(comp["year"], vals, bottom=bottom, width=0.62, linewidth=0,
               color=palette[i], label=agency)
        bottom += vals
    rest = 100.0 - bottom
    ax.bar(comp["year"], rest, bottom=bottom, width=0.62, linewidth=0,
           color=palette[3], label="other")

    ax.set_ylim(0, 100)
    ax.set_ylabel("Share of prime hypocenters (%)")
    ax.set_xlabel("Year")
    # The incomplete year is marked on its own tick rather than above the bar,
    # where the label would collide with the panel title.
    ax.set_xticks(comp["year"].tolist())
    ax.set_xticklabels(["%d\n(partial)" % row["year"] if row["is_partial_year"]
                        else "%d" % row["year"]
                        for _, row in comp.iterrows()])
    ax.legend(frameon=False, fontsize=7, ncol=4, loc="lower center",
              bbox_to_anchor=(0.5, -0.34), columnspacing=1.1, handlelength=1.1,
              handletextpad=0.5)
    ax.set_title("a   The mix turns over again", loc="left", fontsize=8.5, pad=6)

    ax = axes[1]
    recent = ev[ev["period"] == "recent"]
    for row_i, agency in enumerate(order):
        d = recent.loc[recent["agency"] == agency, "depth_km"].dropna().values
        if d.size == 0:
            continue
        # deterministic fan: evenly spaced offsets, no randomness
        spread = np.linspace(-0.28, 0.28, d.size) if d.size > 1 else np.array([0.0])
        flagged = agency in invariant
        ax.scatter(d, row_i + spread, s=7,
                   color=C["colour_series_2"] if flagged else C["colour_series_1"],
                   alpha=0.75 if flagged else 0.45, linewidths=0, zorder=3)

    for row_i, agency in enumerate(order):
        stats = r["by_agency"][agency]
        note = ("one value only" if agency in invariant
                else "%d distinct values" % stats["n_distinct_values"])
        ax.text(50, row_i, note, fontsize=6.8, va="center", ha="right",
                color=C["colour_series_2"] if agency in invariant
                else C["colour_ink_soft"])

    ax.set_yticks(range(len(order)))
    ax.set_yticklabels(["%s (n=%d)" % (a, r["by_agency"][a]["n"]) for a in order])
    ax.set_ylim(-0.7, len(order) - 0.3)
    ax.invert_yaxis()
    # Extra room on the right is reserved for the per-agency annotation so it
    # never overprints a data point.
    ax.set_xlim(-2, 51)
    ax.set_xticks([0, 10, 20, 30, 40])
    ax.set_xlabel("Reported focal depth (km)")
    ax.grid(axis="x", color=C["colour_neutral"], alpha=0.25, lw=0.6)
    ax.set_axisbelow(True)
    ax.set_title("b   Two agencies report a single depth, whatever the event",
                 loc="left", fontsize=8.5, pad=6)

    save(fig, out_dir, "fig07_recent_era")


def main():
    here = os.path.dirname(os.path.abspath(sys.argv[0]))
    p = argparse.ArgumentParser(
        description="Produce the manuscript figures from results.json.")
    p.add_argument("--results", default=os.path.join(here, "..", "output"))
    p.add_argument("--output", default=os.path.join(here, "..", "figures"))
    args = p.parse_args()
    os.makedirs(args.output, exist_ok=True)

    with open(os.path.join(args.results, "results.json"), "r") as fh:
        res = json.load(fh)
    ev = pd.read_csv(os.path.join(args.results, "events_derived.csv"))
    sta = pd.read_csv(os.path.join(args.results, "stations_derived.csv"))
    C = style(res["configuration"])

    print("drawing figures from %s ..." % args.results)
    figure_depth_quantization(res, ev, C, args.output)
    figure_agency_confounding(res, ev, C, args.output)
    figure_gap_versus_cutoff(res, ev, C, args.output)
    figure_network_capability(res, ev, C, args.output)
    figure_recent_era(res, ev, C, args.output)
    figure_station_event_map(res, ev, sta, C, args.output)
    print("done - %s" % args.output)


main()
